### ISSUE TITLE
Empty Kotlin `SourceFileSet` is passed to `JavaPrinter`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/ProtoData#90]
If Kotlin is enabled in a project it causes current language filtering fail because an empty Kotlin-based set is still passed to a `JavaPrinter`.

It can be reproduced in `protodata-extension/.../UuidJavaRenderer.java` class. The PR #87 added a forced check to quit the printing if a file isn't found. If you remove the check the tests would fail with the following diagnostics:

```
> Task :consumer:launchProtoDataMain FAILED
Exception in thread "main" java.lang.IllegalArgumentException: File not found: `io/spine/protodata/test/ProjectId.java`. Source root: `/Users/sanders/Projects/Spine/ProtoData/tests/consumer/build/generated-proto/main/kotlin`. Target root: `/Users/sanders/Projects/Spine/ProtoData/tests/consumer/generated/main/kotlin`.
        at io.spine.protodata.renderer.SourceFileSet.file$lambda$2(SourceFileSet.kt:131)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at io.spine.protodata.renderer.SourceFileSet.file(SourceFileSet.kt:130)
        at io.spine.protodata.test.uuid.UuidJavaRenderer.render(UuidJavaRenderer.java:93)
        at io.spine.protodata.renderer.Renderer.renderSources$compiler(Renderer.kt:54)
```

This happens because `Renderer.renderSources()` creates an empty set (when all `.kt` files are not matched to `.java`), and then the empty set is passed to `UuidJavaRenderer.render()`.

I've added the check for the empty set in `Renderer.renderSource()`. But it does not work inside #87 (as currently integration tests don't seem to use the latest code).

**Comment by alexander-yevsyukov** [comment]
@armiol, @dmdashenkov, FYI.

**Comment by alexander-yevsyukov** [comment]
I've added the check for the empty set in `Renderer.renderSource()`. But it did not work work inside #87 (as currently integration tests don't seem to use the latest code). 

More, it failed one of the tests of `Pipeline`, so I had to remove it.
