### ISSUE TITLE
Unable to add a custom source set like `functionalTest`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/ProtoData#97]
Just tried to arrange a `testFixture` and `functionalTest` source sets in `mc-java-annotations` (following the detekt as an example). Got this:

```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'launchProtoDataFunctionalTest' not found in project ':mc-java-annotation'.
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:102)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:46)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:333)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.getByName(DefaultTaskCollection.java:46)
        at io.spine.protodata.gradle.LaunchTask.get(LaunchTask.kt:50)
        at io.spine.protodata.gradle.plugin.PluginKt$configureProtobufPlugin$1$2.invoke(Plugin.kt:219)
        at io.spine.protodata.gradle.plugin.PluginKt$configureProtobufPlugin$1$2.invoke(Plugin.kt:206)
        at org.gradle.kotlin.dsl.KotlinClosure1.doCall(GroovyInteroperability.kt:94)
        at jdk.internal.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:203)
...
```

If I try to add a dummy task like this:
```kotlin
val launchProtoDataFunctionalTest by tasks.registering {
}
```
I get `ConcurrentModificationException`:

```
A problem occurred configuring project ':mc-java-annotation'.
> java.util.ConcurrentModificationException (no error message)
```

**Comment by alexander-yevsyukov** [comment]
Here's the error with `--stacktrace` enabled: [buildlog.txt](https://github.com/SpineEventEngine/ProtoData/files/9847369/buildlog.txt)
